services:
  client:
    image: "node:22-alpine"
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - WATCHPACK_POLLING=true
  
  server:
    build: ./server
    volumes:
      - ./server:/app
    
    ports:
      - 8000:8000
      
    env_file:
      - ./server/.env.dev.sample
  
  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379

  db:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sms
      - POSTGRES_USER=sms
      - POSTGRES_PASSWORD=password